### ISSUE TITLE
Using SSL

### ISSUE THREAD

**Issue by brendon** [Fingertips/passengerpane#1]
Hi there, I know it's not precisely to do with passengerpane, but I'm wondering if anyone has had experience using it with SSL? I haven't been able to find any good instructions on enabling SSL on osx while still being able to use passengerpane. Do you have any clues on the matter? :D

Cheers,

Brendon

**Comment by alloy** [comment]
Moved from Lighthouse:

Bryan Liles: “It would be nice if passenger helped with ssl setup. SSL requires unique IPs, so you have to create aliased interfaces as well.”

**Comment by alloy** [comment]
@Brendon: You should configure apache and the vhost as normal. The only thing the pane currently does to assist you is allowing you to drag the app from the source list to your text editor to be able to easily edit the vhost. This might change in the future.

**Comment by brendon** [comment]
Thanks Alloy :) You're right, it's quite an involved process on Leopard (though simpler than it used to be I understand). I managed to find some reasonable documentation here: http://raibledesigns.com/rd/entry/apache_2_on_os_x. And yes, if you want to have more than one host you need to do the IP address aliases. Luckily I only needed the one host :)

**Comment by danicuki** [comment]
I'm having problem with ssl too. I've configured my Apache using these instructions: http://superuser.com/questions/73979/how-to-easily-create-a-ssl-certificate-and-configure-it-in-apache2-in-mac-os-x - SSL seems to work (because browser asked to confirm certificate), but when I try to access an https page, it returns "404 Not Found"

**Comment by cthree** [comment]
SSL has nothing to do with this app. Each SSL vhost needs its own IP address. Name based vhosting doesn't work with Apache, IPs only. The pref pane will correctly configure the vhost config but you need to go in to the .conf file with textmate or vi or emacs or whatever you use and change the `<VirtualHost ...>` tag to `<VirtualHost 127.0.0.1:443>` or `<VirtualHost *:443>` if there is only one SSL/TLS vhost config. You also need to add a number of other SSL specific config parameters.

It's unreasonable to expect PrefPane to configure all possible apache vhost config settings for all apache modules.

The scope of the project is up to the maintainers but your best practice is to use this for building quick vhost configs for use in development or as templates. Deploying your vhost to production should be done with a text editor and the production apache config on the production server(s).

**Comment by alloy** [comment]
Very true, thanks for your thoughts chtree. Gonna close the ticket, at least for now.

**Comment by cthree** [comment]
In addition, I suggest you create _2_ config files for SSL enabled sites. The first contains all of the common virtualhost config options for both versions (including what prefpane produces), call it config.inc or something, and then another .conf file which contains two VirtualHost configs which include the first file and any specific options for the vhost, like you SSL certificate info and such.

That way you only really need to maintain one config for both vhosts since the options specific to each vhost isn't going to change much and can be isolated from the actual vhost config.

That's what I do and it makes it very easy to maintain
