### ISSUE TITLE
principalClass is nil error in Snow Leopard

### ISSUE THREAD

**Issue by jschuur** [Fingertips/passengerpane#12]
I tried installing PassengerPane 1.3 into a fresh upgrade of Snow Leopard on top of a virgin Leopard install of a new Macbook Pro, and during the System Preferences install I get a 'Preferences Error. Could not load Passenger preference pane.'

Looking at the Console.app output, I see the following error:

9/7/09 3:40:39 PM   System Preferences[10732]   [NSPrefPaneBundle instantiatePrefPaneObject](/Users/jschuur/Library/PreferencePanes/Passenger.prefPane): principalClass is nil.
9/7/09 3:40:39 PM   [0x0-0x3d23d2].com.apple.systempreferences  2009-09-07 15:40:39.915 System Preferences[10732:903] [NSPrefPaneBundle instantiatePrefPaneObject](/Users/jschuur/Library/PreferencePanes/Passenger.prefPane): principalClass is nil.

FWIW, I'm actually running versions of ruby & Rails from /usr/local and my passenger install is in usr/local/lib/ruby/gems/1.8/gems/passenger-2.2.5/

**Comment by alloy** [comment]
Oh wow, that's nasty. Unfortunately it's such a general error. This basically just means; for some reason during load something went wrong and now the main Class is nil.

I don't think that your custom Ruby and passenger could be the problem. (Unless you removed the system Ruby?) But you could establish that by temporarily removing your custom Ruby from your PATH to see if that makes any difference.

Because this is too hard to debug remotely any further, I'd like to ask you to debug this a bit more. See if you can track down to which part of the source it does actually load.

Thanks

**Comment by jschuur** [comment]
I'd walked away from this for a while, and when I went to check out the preference pane again just now, it magically started working again. I don't think I made any changes to my rails/ruby/apache setup that might have fixed it though. Mac OS 10.6.1 came out, but it's unclear if that's related.

Either way. It's working again now.

**Comment by alloy** [comment]
Ow wow. Well I'm glad for you! Just unfortunate we couldn't get to the bottom of this… 

Anyways, closing for now. Thanks
